# Generated by Django 4.1 on 2022-08-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='user_name',
            field=models.CharField(default='Пользователь', max_length=64),
        ),
    ]
