# Generated by Django 3.2.9 on 2022-09-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_auto_20220904_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='e_mail',
        ),
    ]
