# Generated by Django 4.1 on 2022-08-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_todouser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='user_name',
        ),
    ]
