# Generated by Django 3.2.9 on 2022-08-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0003_remove_todouser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('project_link', models.URLField(blank=True)),
                ('project_users', models.ManyToManyField(to='usersapp.TodoUser')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.TextField()),
                ('todo_creation_date', models.DateTimeField()),
                ('todo_updated_date', models.DateTimeField()),
                ('todo_is_active', models.BooleanField()),
                ('todo_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.todouser')),
                ('todo_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.project')),
            ],
        ),
    ]
