# Generated by Django 3.2.9 on 2022-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_remove_todouser_user_name'),
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_users',
            field=models.ManyToManyField(to='usersapp.TodoUser'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
